version: '3.9'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_upload:/var/www/html/storage/upload
    env_file: .env
    environment:
      - ${LETSENCRYPT_HOST}=${VIRTUAL_HOST}
    # ports:
      # - 8081:${VIRTUAL_PORT}
    expose:
      - ${VIRTUAL_PORT}
    networks:
      - public_shared
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - public_shared
    volumes:
      - firefly_db:/var/lib/mysql

  cron:
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - public_shared

volumes:
   firefly_upload:
   firefly_db:

networks:
  public_shared:
    external: true
      